---
# it may make sense to provide these at the host vars level
ansible_centos_user: centos

ansible_rhel_user: cloud-user

# Java 8 recommended
# Full JDK (not just JRE) recommended. See https://access.redhat.com/solutions/18259
eap_java_pkg_name: java-1.8.0-openjdk-devel

# Override the default method. See https://github.com/rhtconsulting/jboss_eap/blob/master/README.md
transfer_method: csp-to-host  #csp-to-host | copy-from-controller | file-server-to-host


jboss_eap_group: jboss
jboss_eap_user: jboss
jboss_eap_library_dest_dir: /jboss
jboss_eap_home_dir_name: home


jboss_instances:
  - name: cc
  - name: ab
    port_offset: 1
